name: Build

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        dotnet-quality: 'ga'

    - name: Restore tools
      run: dotnet tool restore

    - name: Restore dependencies
      run: dotnet restore

    - name: Check code formatting
      run: dotnet format --no-restore --verify-no-changes

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build test/TinyIpc.Tests
