name: Build

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        dotnet-quality: 'ga'

    - name: Restore tools
      run: dotnet tool restore

    - name: Restore dependencies
      run: dotnet restore

    - name: Check code formatting
      run: dotnet format --no-restore --verify-no-changes

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests (net9.0-windows)
      run: dotnet run --no-build --disable-logo --framework net9.0-windows
      working-directory: test/TinyIpc.Tests

    - name: Run tests (net8.0-windows)
      run: dotnet run --no-build --disable-logo --framework net8.0-windows
      working-directory: test/TinyIpc.Tests

    - name: Run tests (net481)
      run: dotnet run --no-build --disable-logo --framework net481
      working-directory: test/TinyIpc.Tests
